### PR TITLE
update zrmc

### PR DESCRIPTION
**Pull request by lunika**

### CODE REVIEW

**Comment by mikbry** [comment]
I didn't see a console.log in previous PR ?
In advanced.jsx

**Comment by mikbry** [comment]
@lunika you need to remove console.log in advanced.jsx

**Comment by lunika** [comment]
no there is no console.log or console.* in this component. I checked twice after seeing this message on travis.

**Comment by lunika** [comment]
oh in advanced, I checked in AdminManager...

**Pull request merged**
